id: P9BED48B8
initial_creation_type: input
source_metadata:
  title: Tārānamaskāraikaviṃśatistotra
  language: bo
  volumes:
    ae51e8f239e5469b8da1cb97ab6d5a77:
      title: .txt
      base_file: .txt.txt
      work_id: W8302A268
  chapter_to_tile: {}
created_at: '2022-03-01T23:40:18.827350'
last_modified_at: '2022-03-01T23:40:18.827362'
